### ISSUE TITLE
wichtig: Hilfsfunktion

### ISSUE THREAD

**Issue by reneesch** [SsaraBab/Gruppenarbeit-WA#11]
Wir müssen auch unbedingt noch mindestens eine Hilfsfunktion in das Skript 2 schreiben.

Ich denke schon länger darüber nach, aber mir fällt einfach nichts ein, was wir dort rein schreiben könnten. Aber wir dürfen das auf keinen Fall vergessen!

**Comment by SsaraBab** [comment]
Ich bin momentan auch am überlegen, welche Funktion da potenziell passen könnte. Hab ich im Hinterkopf!

**Comment by reneesch** [comment]
Super, Sara, dank deiner Funktion fuer den Modus haben wir nun eine Hilfsfunktion in Skript 2. Ich schließe das Issue damit. :D
