### ISSUE TITLE
Alternative zu f)

### ISSUE THREAD

**Issue by reneesch** [SsaraBab/Gruppenarbeit-WA#12]
Ich bin mit meiner Lösung zu f) noch nicht zufrieden.

Recherche im Internet hat ergeben, dass heatmaps eine schöne Lösung sein können. Es gibt anscheinend auch die Möglichkeit, eine heatmap zu erstellen, obwohl alle Variablen kategoriell sind.

Siehe hier:

[Beispiel einer heatmap mit 3 kategoriellen Variablen](https://stackoverflow.com/questions/51028547/heatmap-of-categorical-variable-counts)

Leider verstehe ich nicht, was dort gemacht wird. Ich bin mir auch nicht sicher, ob wir das fuer unsere Variablen machen könnten, da wir ja im aktuellen Teil explizit keine bestimmten Variablen voraussetzen dürfen, sondern eine allgemeine Funktion schreiben sollen. Aber vielleicht fällt jemandem was ein? 

Der Vorteil wäre wohl, dass die heatmap leichter zu interpretieren wäre.

Die heatmap() Funktion in base r habe ich nicht ans Laufen gekriegt, man kann zwar mit as.matrix(x, y, z) eine Matrix erstellen, aber heatmap() meckert dann, die Matrix sei nicht numerisch, was ja stimmt. Mit der Kontingenztabelle das gleiche Problem.

**Comment by reneesch** [comment]
Habe mittlerweile eine andere Funktion ergänzt: visual.multi.kategoriell2
Die Funktion erstellt Balkendiagramme fuer 3 kategorielle Variablen. Ich finde die Grafik eigentlich ganz gut zu interpretieren. Das Problem ist, dass ich keine Überschrift reinkriege. Vielleicht kriegt das jemand anders hin? Oder sollen wir das sonst einfach so lassen und die Funktion so nehmen? Von den 3 vorhandenen finde ich sie bisher die beste.

@Moshirimozafar Ich verstehe leider nicht, inwiefern deine (?) Funktion visualisierung 3 kategorielle Variablen umfasst. Ich sehe nur eine?

**Comment by reneesch** [comment]
Was jetzt noch offen ist: ich fürchte, dass die Aufgabenstellung zu f) erfordert, dass unsere Funktion flexibel für 3 oder 4 kategorielle Variablen funktionieren soll. Und nicht so, wie es jetzt ist, dass wir uns nur 3 Variablen ausgewählt haben.

Eventuell könnte man visual.multi.kategoriell2 umschreiben, sodass sie 4 Argumente entgegennimmt und ganz zu Anfang mit if einen Check macht und dann verschiedene Dinge tut. Da ich aber nicht weiß, wie man sie für 4 Variablen umschreiben könnte, habe ich das noch nicht gemacht. 

Ich habe diese Woche eine zeitintensive Blockveranstaltung und weiß nicht, ob ich dazu komme. Wäre also gut, wenn jemand anders noch drübergucken könnte!

**Comment by SsaraBab** [comment]
Ich finde die zweite Funktion sehr gut und übersichtlich geschrieben. Habe gerade eine Weile versucht, einen Titel hinzuzufügen, kriege aber nur Fehlermeldungen. Wenn sonst keinem etwas einfällt, müssen wir erstmal ohne leben. 

Der Übersichtlichkeit wegen würde ich eventuell dann die erste Funktion löschen, wenn wir diese ohnehin nicht verwenden, das gleiche gilt für die dritte Funktion mit dem Namen "Visualisierung". 

Heisst das in der Aufgabenstellung beschriebene "Visualisierung von drei oder vier kategorialen Variablen", dass wir eine Funktion für drei und eine für vier erstellen sollen, oder das wir eine für eines der beiden erstellen sollen? Ich bin mir da nicht ganz sicher. Falls es das erstere ist, müssten wir das noch ergänzen.

**Comment by reneesch** [comment]
Hast recht, Sara, die erste Funktion namens visual.multi.kategoriell habe ich soeben gelöscht. Sie läuft zwar, aber das Ergebnis ist einfach zu schwer zu interpretieren. 

Ich bin mir bezüglich deiner letzten Frage auch unsicher, fürchte aber, dass es das erstere ist: entweder eine Funktion, die sowohl 3 als auch 4 Variablen entgegen nehmen kann oder zwei Funktionen, eine fuer 3 Variablen und eine fuer 4. Ich denke, ich schreibe Christina eine Email deswegen und kläre das ab.

**Comment by SsaraBab** [comment]
Eine Funktion für 3 und 4 Variablen ist nun vorhanden, allerdings muss dort noch an der Beschriftung der Diagonalen gearbeitet werden. Momentan steht dort nur "a", "b", "c" und "d", aber eigentlich müssten dort die Namen der Variablen stehen, die in die Funktion eingegeben werden.

**Comment by reneesch** [comment]
Sara und ich haben es geschafft: die Funktion f) läuft endlich mit Titel und Variablennamen in Diagonale bei der Grafik für die 4 Variablen. Ich schließe daher das issue.
