### ISSUE TITLE
wichtig: Teil 4

### ISSUE THREAD

**Issue by reneesch** [SsaraBab/Gruppenarbeit-WA#16]
@Moshirimozafar @MawKi2 @ibrahim-tudo 

Wenn ihr Teil 4 unbedingt jetzt schon bearbeiten wollt, denkt bitte daran, dass wir Teil 3 noch nicht abgeschlossen haben!

Sara hat gerade noch etwas gemacht, aber es sind noch offen: 
- eine weitere deskriptive Statistik fuer d), dazu ist ein Vorschlag im issue "Ergebnisausgabe c) und d)"
- die Funktion in f) erweitern, sodass sie auch für 4 und nicht nur für 3 Variablen funktioniert, s. issue "Alternative zu f)"

Ich hatte leider noch keine Zeit, meine Vorschläge umzusetzen, da ich diese Woche eine zeitintensive Blockveranstaltung habe. 
Es wäre gut, wenn da jemand von euch nochmal drüberguckt, bitte.

**Comment by reneesch** [comment]
Danke an alle Beteiligten, Teil 3 ist nun offiziell fertig. :-)

Meldet ihr euch hier am besten, wenn ihr mit Teil 4 fertig seid?

Damit wir die Ergebnisse noch diskutieren können, wie es in Teil 5 gefordert ist.

**Comment by Moshirimozafar** [comment]
Danke an alle :)
R-Skript 4 ist fast fertig, wir haben nur kleine Errors und versuchen so bald wie möglich diese kleine Errors auch zu lösen und alles offiziell zur Ende zu bringen ;)

**Comment by Moshirimozafar** [comment]
Alles ist in Ordnung, glube ich ;)
