### ISSUE TITLE
Redundanz in Teil 4 Anwendung von Funktion b

### ISSUE THREAD

**Issue by MawKi2** [SsaraBab/Gruppenarbeit-WA#22]
Da wie bereits besprochen in [R-Skript 4 - (Aufgabe 4).R] eine Redundanz beim Funktionsaufruf existiert Folgenden Code zu löschen:

function(kategoriell)
  
  Datensatz$Studienfach <- c(rep(c("Statistic", "Data Science", "informatik", "Mathe"), c(31,37,25,7)))
kategoriell(Datensatz$Studienfach)

**Comment by Moshirimozafar** [comment]
Das stimmt...
Das war irgendwie HardCode ;)

**Comment by Moshirimozafar** [comment]
@MawKi2 
Ich konnte leider die Änderungen, die von dir durchgeführt sind, nicht gefunden.
Deswegen habe ich ein paar Korrekturen gemacht und dir Review bzw. Pull request gegeben ;)

**Comment by Moshirimozafar** [comment]
Ich habe Conflict gefunden ;)
