### ISSUE TITLE
Funktion fuer metrische Variablen

### ISSUE THREAD

**Issue by reneesch** [SsaraBab/Gruppenarbeit-WA#7]
Ich kriege den letzten empty space in der Ergebnisausgabe der Funktion von (a) leider nicht weg. 

Faellt jemandem noch interessante deskriptive Statistiken fuer metrische Variablen ein, die nicht arithmetisches Mittel oder Standardabweichung sind?  Wenn ja, gerne ergaenzen.

**Comment by SsaraBab** [comment]
Da das Problem mit den Spaces gelöst ist schließe ich dieses Issue mal. Falls noch jemand desktiptive Statistiken einfallen, die nicht in der Funktion sind, können die ja weiterhin ergänzt werden, wie bei allen anderen Funktionen a) bis f)
