### ISSUE TITLE
Ergebnisausgabe bei c) und d)

### ISSUE THREAD

**Issue by SsaraBab** [SsaraBab/Gruppenarbeit-WA#9]
Ähnlich wie bei Aufgabe b) (siehe Issue zu Funktion von kategoriellen Variablen) fehlt auch hier die richtige Ergebnisausgabe, da ich mir nicht sicher bin, ob wir die Häufigkeitstabelle ausgeben sollen oder das ganze als Auflistung oder Satz ausgeben wollen. 
(Ebenso können hier noch weitere Funktionsteile zur Analyse ergänzt werden.)

**Comment by MawKi2** [comment]
Ich denke bei allen Funktionen reicht die Ausgabe der Daten, da wir damit in der letzten Aufgabe die Analyse durchführen sollen.

**Comment by reneesch** [comment]
Ich finde auch, dass das so gut aussieht. Allerdings steht in d) etwas von "verschiedene deskriptive bivariate Statistiken" und in c) ist es auch im Plural. Wir haben ja bisher nur eine. Ich versuche gerade, noch mehr zu finden, aber bisher ist mir nix eingefallen.

**Comment by reneesch** [comment]
Mir ist zu c) noch eingefallen, dass wir die Tabelle aus b) verwenden könnten, aber dann mit den Randsummen dazu, und das zusätzlich für c) ausgeben. 

Für d) könnte man zusätzlich noch den Mittelwert der metrischen Variable für die zwei Untergruppen der dichotomen Variablen berechnen sowie den Unterschied zwischen beiden, und das bei der Ergebnisausgabe ergänzen.

Ich hatte leider noch keine Zeit, das umzusetzen. Hoffentlich morgen oder jemand anderes ist schneller ;-)

**Comment by SsaraBab** [comment]
Bei c) habe ich versucht die Randsummen zu ergänzen, kriege aber eine Fehlermeldung: 

Warning message:
In cbind(h, hkum) :
  number of rows of result is not a multiple of vector length (arg 2)

Bin mir nicht so ganz sicher, was genau das Problem ist, aber ich glaube, ich habe eventuell eine falsche Funktion benutzt. Im Zweifelsfall müssten wir den Versuch löschen und es nochmal anders versuchen

**Comment by SsaraBab** [comment]
Okay, ich habe das jetzt mit den Zeilensummen zum Laufen gekriegt, falls noch jemand Spaltensummen möchte, dass hat bei mir irgendwie nicht so ganz funktioniert.

**Comment by reneesch** [comment]
Das geht fuer abs. Haeufigkeiten eigentlich sehr einfach fuer beide Arten von Randsummen mit
H_rand <- addmargins(H, margin = c(1,2))
 
Der Grund, warum ich es nicht ergaenzt habe, ist der, dass dann h, also die Tafel fuer die relativen Haeufigkeiten natuerlich eine Zeile weniger hat (die Spaltensummen) und ich es dann mit cbind nicht hingekriegt habe, beide zusammen auszugeben. Eventuell koennte man eine Zeile in h mit NA erzeugen? Ich habe versucht, analog zu machen
h_rand <- addmargins(h, margin = c(1,2))
aber dann kamen da rel. Haeufigkeiten von groesser als 1, das ist also falsch.

Hatte leider noch keine Zeit, meine Vorschläge für d) umzusetzen. Vielleicht könnte das jemand anders versuchen? @MawKi2 ? Falls du demnächst Zeit hast? Siehe oben hier im selben issue.

**Comment by SsaraBab** [comment]
Ich habe jetzt bei c) die Reihen- und Spaltensummen sowohl bei relativen als auch bei absoluten Häufigkeiten ergänzt, sodass auch beides in einem Frame ausgegeben wird. Eventuell könnte man an der Beschriftung noch etwas ändern, wirkt aber auf mich verständlich. (Copy von meinem Summary zu diesem Part)

**Comment by reneesch** [comment]
Danke an wen auch immer, der in d) den gewuenschten Mittelwert nach der dichotomen Variable aufgeteilt ergaenzt hat! 
Hab gerade paar Kleinigkeiten noch angepasst: die Funktion kommentiert und die Variablennamen benannt, wie sie oben in der Funktion heißen. Ich schließe das issue nun. Juchu!
